syntax = "proto3";

package todo;

// Specifies the Go package path where the generated code will live
option go_package = "github.com/MRNaveed-stack/rpc-gRPC--practice-with-projects/proto/pb";

service TodoService {
  rpc CreateTask (CreateTaskRequest) returns (CreateTaskResponse);
  rpc GetTask (GetTaskRequest) returns (Task);
  rpc ListTasks (ListTasksRequest) returns (ListTasksResponse);
}

message Task {
  string id = 1;
  string title = 2;
  string description = 3;
  bool completed = 4;
}

message CreateTaskRequest {
  string title = 1;
  string description = 2;
}

message CreateTaskResponse {
  Task task = 1;
}

message GetTaskRequest {
  string id = 1;
}

message ListTasksRequest {}

message ListTasksResponse {
  repeated Task tasks = 1;
}